[versions]
quarkus = "3.31.2"
quarkus-amazon = "3.14.1"
spotless = "8.2.1"

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-amazon-bom = { module = "io.quarkiverse.amazonservices:quarkus-amazon-services-bom", version.ref = "quarkus-amazon" }

# Quarkus extensions
quarkus-config-yaml = { module = "io.quarkus:quarkus-config-yaml" }
quarkus-rest-jackson = { module = "io.quarkus:quarkus-rest-jackson", version.ref = "quarkus" }
quarkus-rest-client-jackson = { module = "io.quarkus:quarkus-rest-client-jackson" }
quarkus-messaging-kafka = { module = "io.quarkus:quarkus-messaging-kafka", version.ref = "quarkus" }
quarkus-smallrye-openapi = { module = "io.quarkus:quarkus-smallrye-openapi", version.ref = "quarkus" }
quarkus-smallrye-fault-tolerance = { module = "io.quarkus:quarkus-smallrye-fault-tolerance", version.ref = "quarkus" }

# Quarkiverse Amazon services
quarkus-amazon-s3 = { module = "io.quarkiverse.amazonservices:quarkus-amazon-s3" }
aws-url-connection-client = { module = "software.amazon.awssdk:url-connection-client" }

# Jakarta common
jakarta-ws-rs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version = "4.0.0" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version = "3.0.0" }

# OpenAPI
quarkus-openapi-generator = { module = "io.quarkiverse.openapi.generator:quarkus-openapi-generator", version = "2.14.0" }
